
nodeLinker: pnp

supportedArchitectures:
  cpu:
    - current
    - arm64
    - x64
  libc:
    - current
    - glibc
    - musl
  os:
    - darwin
    - linux
    - current
    - ubuntu

yarnPath: .yarn/releases/yarn-3.2.3.cjs
