export enum RoomEventType {
  CREATE = "create",
  DELETED = "delete",
  UPDATE = "update",
  USER_ENTER = "userJoin",
  USER_LEAVE = "userLeave",
  USER_KICKED = "userKicked",
  ALL_READY = "allReady",
  ALL_READY_CANCELED = "allReadyCanceled",
  ORDER_FIXED = "orderFix",
  ORDER_CHECKED = "orderCheck",
  ORDER_DONE = "orderDone",
  KICK_VOTE_CREATED = "kickVoteCreated",
  KICK_VOTE_FINISHED = "kickVoteFinished",
  RESET_VOTE_CREATED = "resetVoteCreated",
  RESET_VOTE_FINISHED = "resetVoteFinished",
  CHAT = "chat",
}
