export enum CategoryType {
  KOREAN = "korean",
  CHINESE = "chinese",
  JAPANESE = "japanese",
  WESTERN = "western",
  PORKCUTLET = "porkcutlet",
  CHICKEN = "chicken",
  PIZZA = "pizza",
  DDEOCK = "ddeock",
  FASTFOOD = "fastfood",
  DESSERT = "dessert",
  ETC = "etc",
  ASIAN = "asia",
  JOKBO = "jokbo",
}
